"use client";

import { AnimatePresence, motion } from "framer-motion";
import { Check, Copy, Flame, Mail, ShieldCheck, X } from "lucide-react";
import { useState } from "react";
import type { Prospect } from "@/lib/types";

const labels: [keyof Prospect["score_breakdown"], string, number][] = [["icp_fit", "ICP fit", 30], ["company_fit", "Company fit", 20], ["buying_signals", "Buying signals", 25], ["decision_maker", "Decision maker", 15], ["evidence_quality", "Evidence quality", 10]];

export function ProspectDetail({ prospect, approved, onClose, onApprove }: { prospect: Prospect | null; approved: boolean; onClose: () => void; onApprove: () => void }) {
  const [tab, setTab] = useState<"research" | "outreach">("research");
  const [copied, setCopied] = useState(false);
  if (!prospect) return null;
  return <AnimatePresence><motion.div className="detail-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={onClose}><motion.aside className="detail" initial={{ x: 40 }} animate={{ x: 0 }} exit={{ x: 40 }} onMouseDown={(e) => e.stopPropagation()}><header><div><span className="detail-overline">RESEARCH BRIEF · DEMO DATA</span><h2>{prospect.company}</h2><p>{prospect.description}</p></div><button aria-label="Close research brief" className="close" onClick={onClose}><X size={19} /></button></header><div className="detail-tabs"><button className={tab === "research" ? "selected" : ""} onClick={() => setTab("research")}>Research brief</button><button className={tab === "outreach" ? "selected" : ""} onClick={() => setTab("outreach")}>Outreach sequence</button></div>
  {tab === "research" ? <div className="detail-content"><section className="why"><div className="score large"><strong>{prospect.score}</strong><span>/100<br />opportunity score</span></div><div><span className="section-label">WHY THIS COMPANY</span><p>{prospect.research_summary}</p></div></section><section><span className="section-label">BUYING SIGNALS</span>{prospect.buying_signals.map((signal) => <div className="evidence-row" key={signal.text}><Flame size={17} /><div><b>{signal.text}</b><p>{signal.source} · <strong>{Math.round(signal.confidence * 100)}% confidence</strong></p></div></div>)}</section><section><span className="section-label">DECISION MAKER</span><div className="decision-maker"><div className="person-avatar big">{prospect.decision_maker.name.slice(0, 1)}</div><div><b>{prospect.decision_maker.name}</b><p>{prospect.decision_maker.role} · {Math.round(prospect.decision_maker.confidence * 100)}% confidence</p><p className="muted"><Mail size={13} /> Email not publicly verified</p></div></div></section><section><span className="section-label">EVIDENCE & TRUST</span>{prospect.evidence.map((evidence) => <div className="trust" key={evidence.fact}><div><ShieldCheck size={15} /> FACT</div><p>{evidence.fact}</p><div>INFERENCE</div><p>{evidence.inference}</p><footer><span>{evidence.confidence} confidence</span><span>{evidence.source}</span></footer></div>)}</section><section><span className="section-label">SCORE BREAKDOWN</span>{labels.map(([key, label, max]) => <div className="breakdown" key={key}><span>{label}</span><i><b style={{ width: `${prospect.score_breakdown[key] / max * 100}%` }} /></i><strong>{prospect.score_breakdown[key]}/{max}</strong></div>)}</section></div> : <div className="detail-content outreach"><div className="outreach-note"><ShieldCheck size={16} /> Each note only references the signals shown in this brief.</div>{prospect.outreach.map((step) => <article className="email-step" key={step.day}><header><span>DAY {step.day}</span><button onClick={() => { navigator.clipboard.writeText(step.body); setCopied(true); setTimeout(() => setCopied(false), 1400); }}><Copy size={14} /> {copied ? "Copied" : "Copy"}</button></header><b>{step.subject}</b><p>{step.body}</p></article>)}</div>}<footer className="detail-footer"><button className="secondary" onClick={() => setTab(tab === "research" ? "outreach" : "research")}>{tab === "research" ? "Review outreach" : "Back to research"}</button><button className={`primary ${approved ? "queued" : ""}`} onClick={onApprove}>{approved ? <><Check size={16} /> Added to queue</> : "Approve & send"}</button></footer></motion.aside></motion.div></AnimatePresence>;
}
